### ISSUE TITLE
NPM Error: @sap/xb-msg-amqp-v100 not found (^0.3.5)

### ISSUE THREAD

**Issue by edersouza38** [SAP/enterprise-messaging-client-nodejs-samples#1]
Hello,
I've tried to compile the provided Node.js examples but I've run into a problem when I tried to install the package dependencies using **npm install**:

npm ERR! 404 Not Found: @sap/xb-msg-amqp-v100@^**0.3.5**

I am not sure if I made something wrong, but it seems that the available version from @sap/xb-msg-amqp-v100 in https://npm.sap.com doesn't satisfy the required dependencies:

PS C:\Users\XXXXX\Documents\SAP\SAP Enterprise Messaging\client-nodejs-samples\xb-msg-amqp-v100-samples> npm search --registry https://npm.sap.com amqp
npm ERR! registry error parsing json
npm WARN search fast search endpoint errored. Using old search.
NAME                      | DESCRIPTION          | AUTHOR          | DATE       | **VERSION**  | KEYWORDS
@sap/xb-msg-amqp-v091     | XB Messaging AMQP…   | =https-support… | 2018-05-02 | **0.2.0**    |
@sap/xb-msg-amqp-v100     | XB Messaging AMQP…   | =https-support… | 2018-05-02 | **0.1.0**    |

Best regards,
Éder

**Comment by jonathanbaker7** [comment]
**AS-IS project warning**

This is just to make sure you are aware of the support status.

The README for this project states the team is not supporting the sample, and the code is delivered "as-is".  We can't guarantee that anyone will get back to you.  

Feel free to leave this open, if you wish.

**Comment by edersouza38** [comment]
Hi Jonathan,

Thanks for the feedback, I just wanted to draw your attention to this issue in SAP NPM. I'll close this issue, but I just wanted to know if I can keep at least giving you guys a head up through a new issue, in case I run into new problems in the future. 

Best regards,
Éder

**Comment by EdoB** [comment]
To anyone in the future who wonder how to fix this.

Just run `npm install @sap/xb-msg-amqp-v100@latest`
